language: php

cache:
    directories:
        $HOME/.composer/cache/files

php:
    - 7.0

install:
    - php -n ~/.phpenv/versions/$(phpenv version-name)/bin/composer self-update
    - php -n ~/.phpenv/versions/$(phpenv version-name)/bin/composer update

script:
    - php -n ~/.phpenv/versions/$(phpenv version-name)/bin/composer lint
